@isTest
public class DisableResponseTest {

    /**
    * Test method to enhance code coverage for Apex Models; This ain't validating any specific business use case.
    * Enhances code coverage for DisableResponse apex class
    */
    @isTest
    private static void testAllMethodsFromDisableResponse(){
        DisableResponse dResp = new DisableResponse();
        dResp.response = 'TESTSTRING';
    }
}